

services:
  db:
    image: postgres:latest
    container_name: patient-db
    environment:
      POSTGRES_DB: patient_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  patient-service:
    build: ./patient-service
    container_name: patient-service
    depends_on:
      - db
      - kafka
      - billing-service

    environment:
      DB_URL: jdbc:postgresql://db:5432/patient_db
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      BILLING_GRPC_HOST: billing-service
      BILLING_GRPC_PORT: 9001
    # ports:
    #   - "8081:8080"

  billing-service:
    build: ./billing-serivce
    container_name: billing-service
    ports:
      - "8085:8085"  # HTTP port
      - "9001:9001"  # gRPC port
    environment:
      SPRING_APPLICATION_NAME: billing-serivce

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      
      # Listeners
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      
      # Inter-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Single-node dev safety
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Required for KRaft
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    ports:
      - "8088:8087"  # HTTP port
      - "9004:9003"  # gRPC port
    environment:
      SPRING_APPLICATION_NAME: analytics-service
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092


  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "4004:4004"
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    volumes:
      - ./gateway-service/src/main/resources/application.yml:/app/application.yml
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - auth-db

    environment:
      DB_URL: jdbc:postgresql://auth-db:5432/auth-db
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}


volumes:
  postgres-data:
  auth-data:
